version: '3.8'

services:
    frontend:
        build:
            dockerfile: ../docker/Dockerfile.frontend
        command: bash -c "cd app/frontend && trunk serve --address 0.0.0.0 --port ${FRONTEND_PORT:-80}"
        environment:
            - BACKEND_PORT=${BACKEND_PORT:-8080}
            - FRONTEND_PORT=${FRONTEND_PORT:-80}
            - ENABLE_OAUTH=true
            - LOGIN_URL=http://localhost:${BACKEND_PORT:-8080}/login
        volumes:
            - type: bind
              source: ../
              target: /app
            - /app/frontend/target
        ports:
            - "${FRONTEND_PORT:-80}:${FRONTEND_PORT:-80}"

    backend:
        build:
            dockerfile: ../docker/Dockerfile.backend
        command: bash -c "cd app/backend && cargo watch -x \"run\""
        depends_on:
            - postgres
        environment:
            - BACKEND_PORT=${BACKEND_PORT:-8080}
            - FRONTEND_PORT=${FRONTEND_PORT:-80}
            - FRONTEND_HOST=localhost
            - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
            - OAUTH_AUTH_URL=${OAUTH_AUTH_URL}
            - OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL}
            - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
            - OAUTH_REDIRECT_URL=http://localhost:${BACKEND_PORT:-8080}/login/callback
            - RUST_LOG=info
            - PG_URL=postgres://postgres:docker@postgres:5432/backend-db?sslmode=disable
        volumes:
            - type: bind
              source: ../
              target: /app
            - /app/backend/target
        ports:
            - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"

    dbmate:
        build:
            context: ../dbmate
        depends_on:
            - postgres
        environment:
            DATABASE_URL: "postgres://postgres:docker@postgres:5432/backend-db?sslmode=disable"
        volumes:
            - ../dbmate/db:/app/db

    postgres:
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: "docker"
            PGPASSWORD: "docker"
        ports:
            - 5432
